#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Klash_V2.Resource", IsApplication=true)]

namespace Klash_V2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000e
			public const int button1 = 2130968590;
			
			// aapt resource value: 0x7f040010
			public const int button2 = 2130968592;
			
			// aapt resource value: 0x7f040000
			public const int editText1 = 2130968576;
			
			// aapt resource value: 0x7f04000d
			public const int imageView1 = 2130968589;
			
			// aapt resource value: 0x7f040006
			public const int loginBut = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int password = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int passwordText = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int playerData = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int registerButton = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int rememberMe = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public const int scheduleButton = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int teamData = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int testLogin = 2130968583;
			
			// aapt resource value: 0x7f04000f
			public const int textView1 = 2130968591;
			
			// aapt resource value: 0x7f04000c
			public const int tourneyData = 2130968588;
			
			// aapt resource value: 0x7f040002
			public const int username = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int usernameText = 2130968577;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int match = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int matchData = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int menuActivity = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int playerView = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int scheduleView = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int teamView = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int tourneyData = 2130837511;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
